# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import AccessRequestsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("access-requests")
def access_requests_group() -> None:
    """AccessRequests commands."""


@access_requests_group.command("approve-access-request")
@click.argument("access_request_gid")
@formatted
def approve_access_request(access_request_gid: str) -> Any:
    """Approve an access request"""
    session = AsanaSession.from_env()
    api = AccessRequestsApi(session.client)
    opts: dict[str, Any] = {}
    return api.approve_access_request(access_request_gid)


@access_requests_group.command("create-access-request")
@click.option("--body", required=True, help="If the method is called asynchronously, returns the request thread.")
@formatted
def create_access_request(body: str) -> Any:
    """Create an access request"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = AccessRequestsApi(session.client)
    opts: dict[str, Any] = {}
    return api.create_access_request(parsed_body)


@access_requests_group.command("get-access-requests")
@click.argument("target")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--user", default=None, help="A string identifying a user. This can either be the string \"me\", an email, or the gid of a user.")
@formatted
def get_access_requests(target: str, opt_fields: str | None, user: str | None) -> Any:
    """Get access requests"""
    session = AsanaSession.from_env()
    api = AccessRequestsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if user is not None:
        opts["user"] = user
    return api.get_access_requests(target, opts)


@access_requests_group.command("reject-access-request")
@click.argument("access_request_gid")
@formatted
def reject_access_request(access_request_gid: str) -> Any:
    """Reject an access request"""
    session = AsanaSession.from_env()
    api = AccessRequestsApi(session.client)
    opts: dict[str, Any] = {}
    return api.reject_access_request(access_request_gid)
