# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import AttachmentsApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("attachments", cls=GroupWithGlobalOptions)
def attachments_group() -> None:
    """Attachments commands."""


@attachments_group.command("create-attachment-for-object")
@click.option("--connect-to-app", type=bool, default=None, help="")
@click.option("--file", default=None, help="")
@click.option("--name", default=None, help="")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--parent", default=None, help="")
@click.option("--resource-subtype", default=None, help="")
@click.option("--url", default=None, help="")
@formatted
def create_attachment_for_object(connect_to_app: bool | None, file: str | None, name: str | None, opt_fields: str | None, parent: str | None, resource_subtype: str | None, url: str | None) -> Any:
    """Upload an attachment"""
    session = AsanaSession.from_env()
    api = AttachmentsApi(session.client)
    opts: dict[str, Any] = {}
    if connect_to_app is not None:
        opts["connect_to_app"] = connect_to_app
    if file is not None:
        opts["file"] = file
    if name is not None:
        opts["name"] = name
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if parent is not None:
        opts["parent"] = parent
    if resource_subtype is not None:
        opts["resource_subtype"] = resource_subtype
    if url is not None:
        opts["url"] = url
    return api.create_attachment_for_object(opts)


@attachments_group.command("delete-attachment")
@click.option("--attachment", required=True, help="Globally unique identifier for the attachment. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_attachment(attachment: str) -> Any:
    """Delete an attachment"""
    session = AsanaSession.from_env()
    api = AttachmentsApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_attachment(attachment)


@attachments_group.command("get-attachment")
@click.option("--attachment", required=True, help="Globally unique identifier for the attachment.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_attachment(attachment: str, opt_fields: str | None) -> Any:
    """Get an attachment"""
    session = AsanaSession.from_env()
    api = AttachmentsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_attachment(attachment, opts)


@attachments_group.command("get-attachments-for-object")
@click.option("--parent", required=True, help="Globally unique identifier for object to fetch statuses from. Must be a GID for a `project`, `project_brief`, or `task`.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_attachments_for_object(parent: str, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get attachments from an object"""
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = AttachmentsApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_attachments_for_object, parent, opts=opts, max_items=max_items)
    return api.get_attachments_for_object(parent, opts)
