# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import BudgetsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("budgets")
def budgets_group() -> None:
    """Budgets commands."""


@budgets_group.command("create-budget")
@click.option("--body", required=True, help="The budget to create. If the method is called asynchronously, returns the request thread.")
@formatted
def create_budget(body: str) -> Any:
    """Create a budget"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = BudgetsApi(session.client)
    opts: dict[str, Any] = {}
    return api.create_budget(parsed_body)


@budgets_group.command("delete-budget")
@click.argument("budget_gid")
@formatted
def delete_budget(budget_gid: str) -> Any:
    """Delete a budget"""
    session = AsanaSession.from_env()
    api = BudgetsApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_budget(budget_gid)


@budgets_group.command("get-budget")
@click.argument("budget_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_budget(budget_gid: str, opt_fields: str | None) -> Any:
    """Get a budget"""
    session = AsanaSession.from_env()
    api = BudgetsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_budget(budget_gid, opts)


@budgets_group.command("get-budgets")
@click.argument("parent")
@formatted
def get_budgets(parent: str) -> Any:
    """Get all budgets"""
    session = AsanaSession.from_env()
    api = BudgetsApi(session.client)
    opts: dict[str, Any] = {}
    return api.get_budgets(parent)


@budgets_group.command("update-budget")
@click.argument("budget_gid")
@click.option("--body", required=True, help="The budget to update.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_budget(budget_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a budget"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = BudgetsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_budget(parsed_body, budget_gid, opts)
