# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import CustomFieldSettingsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("custom-field-settings")
def custom_field_settings_group() -> None:
    """CustomFieldSettings commands."""


@custom_field_settings_group.command("get-custom-field-settings-for-goal")
@click.argument("goal_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_custom_field_settings_for_goal(goal_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get a goal's custom fields"""
    session = AsanaSession.from_env(paginate=paginate)
    api = CustomFieldSettingsApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_custom_field_settings_for_goal(goal_gid, opts)


@custom_field_settings_group.command("get-custom-field-settings-for-portfolio")
@click.argument("portfolio_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_custom_field_settings_for_portfolio(portfolio_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get a portfolio's custom fields"""
    session = AsanaSession.from_env(paginate=paginate)
    api = CustomFieldSettingsApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_custom_field_settings_for_portfolio(portfolio_gid, opts)


@custom_field_settings_group.command("get-custom-field-settings-for-project")
@click.argument("project_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_custom_field_settings_for_project(project_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get a project's custom fields"""
    session = AsanaSession.from_env(paginate=paginate)
    api = CustomFieldSettingsApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_custom_field_settings_for_project(project_gid, opts)


@custom_field_settings_group.command("get-custom-field-settings-for-team")
@click.argument("team_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_custom_field_settings_for_team(team_gid: str, opt_fields: str | None) -> Any:
    """Get a team's custom fields"""
    session = AsanaSession.from_env()
    api = CustomFieldSettingsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_custom_field_settings_for_team(team_gid, opts)
