# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import EventsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("events")
def events_group() -> None:
    """Events commands."""


@events_group.command("get-events")
@click.argument("resource")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--sync", default=None, help="A sync token received from the last request, or none on first sync. Events will be returned from the point in time that the sync token was generated. *Note: On your first request, omit the sync tok...")
@formatted
def get_events(resource: str, opt_fields: str | None, sync: str | None) -> Any:
    """Get events on a resource"""
    session = AsanaSession.from_env()
    api = EventsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if sync is not None:
        opts["sync"] = sync
    return api.get_events(resource, opts)
