# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import GoalsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("goals")
def goals_group() -> None:
    """Goals commands."""


@goals_group.command("add-custom-field-setting-for-goal")
@click.argument("goal_gid")
@click.option("--body", required=True, help="Information about the custom field setting.")
@formatted
def add_custom_field_setting_for_goal(goal_gid: str, body: str) -> Any:
    """Add a custom field to a goal"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_custom_field_setting_for_goal(parsed_body, goal_gid)


@goals_group.command("add-followers")
@click.argument("goal_gid")
@click.option("--body", required=True, help="The followers to be added as collaborators")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_followers(goal_gid: str, body: str, opt_fields: str | None) -> Any:
    """Add a collaborator to a goal"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_followers(parsed_body, goal_gid, opts)


@goals_group.command("create-goal")
@click.option("--body", required=True, help="The goal to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_goal(body: str, opt_fields: str | None) -> Any:
    """Create a goal"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_goal(parsed_body, opts)


@goals_group.command("create-goal-metric")
@click.argument("goal_gid")
@click.option("--body", required=True, help="The goal metric to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_goal_metric(goal_gid: str, body: str, opt_fields: str | None) -> Any:
    """Create a goal metric"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_goal_metric(parsed_body, goal_gid, opts)


@goals_group.command("delete-goal")
@click.argument("goal_gid")
@formatted
def delete_goal(goal_gid: str) -> Any:
    """Delete a goal"""
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_goal(goal_gid)


@goals_group.command("get-goal")
@click.argument("goal_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_goal(goal_gid: str, opt_fields: str | None) -> Any:
    """Get a goal"""
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_goal(goal_gid, opts)


@goals_group.command("get-goals")
@click.option("--is-workspace-level", type=bool, default=None, help="Filter to goals with is_workspace_level set to query value. Must be used with the workspace parameter.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--portfolio", default=None, help="Globally unique identifier for supporting portfolio.")
@click.option("--project", default=None, help="Globally unique identifier for supporting project.")
@click.option("--task", default=None, help="Globally unique identifier for supporting task.")
@click.option("--team", default=None, help="Globally unique identifier for the team.")
@click.option("--time-periods", default=None, help="Globally unique identifiers for the time periods.")
@click.option("--workspace", default=None, help="Globally unique identifier for the workspace.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_goals(is_workspace_level: bool | None, limit: int | None, offset: str | None, opt_fields: str | None, portfolio: str | None, project: str | None, task: str | None, team: str | None, time_periods: str | None, workspace: str | None, paginate: bool) -> Any:
    """Get goals"""
    session = AsanaSession.from_env(paginate=paginate)
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if is_workspace_level is not None:
        opts["is_workspace_level"] = is_workspace_level
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if portfolio is not None:
        opts["portfolio"] = portfolio
    if project is not None:
        opts["project"] = project
    if task is not None:
        opts["task"] = task
    if team is not None:
        opts["team"] = team
    if time_periods is not None:
        opts["time_periods"] = time_periods
    if workspace is not None:
        opts["workspace"] = workspace
    return api.get_goals(opts)


@goals_group.command("get-parent-goals-for-goal")
@click.argument("goal_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_parent_goals_for_goal(goal_gid: str, opt_fields: str | None) -> Any:
    """Get parent goals from a goal"""
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_parent_goals_for_goal(goal_gid, opts)


@goals_group.command("remove-custom-field-setting-for-goal")
@click.argument("goal_gid")
@click.option("--body", required=True, help="Information about the custom field setting being removed.")
@formatted
def remove_custom_field_setting_for_goal(goal_gid: str, body: str) -> Any:
    """Remove a custom field from a goal"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_custom_field_setting_for_goal(parsed_body, goal_gid)


@goals_group.command("remove-followers")
@click.argument("goal_gid")
@click.option("--body", required=True, help="The followers to be removed as collaborators")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def remove_followers(goal_gid: str, body: str, opt_fields: str | None) -> Any:
    """Remove a collaborator from a goal"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.remove_followers(parsed_body, goal_gid, opts)


@goals_group.command("update-goal")
@click.argument("goal_gid")
@click.option("--body", required=True, help="The updated fields for the goal.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_goal(goal_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a goal"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_goal(parsed_body, goal_gid, opts)


@goals_group.command("update-goal-metric")
@click.argument("goal_gid")
@click.option("--body", required=True, help="The updated fields for the goal metric.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_goal_metric(goal_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a goal metric"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = GoalsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_goal_metric(parsed_body, goal_gid, opts)
