# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import MembershipsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("memberships")
def memberships_group() -> None:
    """Memberships commands."""


@memberships_group.command("create-membership")
@formatted
def create_membership() -> Any:
    """Create a membership"""
    session = AsanaSession.from_env()
    api = MembershipsApi(session.client)
    opts: dict[str, Any] = {}
    return api.create_membership(opts)


@memberships_group.command("delete-membership")
@click.argument("membership_gid")
@formatted
def delete_membership(membership_gid: str) -> Any:
    """Delete a membership"""
    session = AsanaSession.from_env()
    api = MembershipsApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_membership(membership_gid)


@memberships_group.command("get-membership")
@click.argument("membership_gid")
@formatted
def get_membership(membership_gid: str) -> Any:
    """Get a membership"""
    session = AsanaSession.from_env()
    api = MembershipsApi(session.client)
    opts: dict[str, Any] = {}
    return api.get_membership(membership_gid)


@memberships_group.command("get-memberships")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--member", default=None, help="Globally unique identifier for `team` or `user`. When used with `resource_subtype` and without `parent`, returns all memberships of the specified subtype for this member.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--parent", default=None, help="Globally unique identifier for `goal`, `project`, `portfolio`, `custom_type`, or `custom_field`. This parameter is optional when `resource_subtype` is provided along with `member`.")
@click.option("--resource-subtype", default=None, help="The type of membership to return. Required when `parent` is absent. Currently supported value is `project_membership` (when `member` is a team GID, returns all project memberships for that team).")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_memberships(limit: int | None, member: str | None, offset: str | None, opt_fields: str | None, parent: str | None, resource_subtype: str | None, paginate: bool) -> Any:
    """Get multiple memberships"""
    session = AsanaSession.from_env(paginate=paginate)
    api = MembershipsApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if member is not None:
        opts["member"] = member
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if parent is not None:
        opts["parent"] = parent
    if resource_subtype is not None:
        opts["resource_subtype"] = resource_subtype
    return api.get_memberships(opts)


@memberships_group.command("update-membership")
@click.argument("membership_gid")
@click.option("--body", required=True, help="The membership to update.")
@formatted
def update_membership(membership_gid: str, body: str) -> Any:
    """Update a membership"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = MembershipsApi(session.client)
    opts: dict[str, Any] = {}
    return api.update_membership(parsed_body, membership_gid)
