# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import PortfoliosApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("portfolios", cls=GroupWithGlobalOptions)
def portfolios_group() -> None:
    """Portfolios commands."""


@portfolios_group.command("add-custom-field-setting-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio. If the method is called asynchronously, returns the request thread.")
@click.option("--body", required=True, help="Information about the custom field setting.")
@formatted
def add_custom_field_setting_for_portfolio(portfolio: str, body: str) -> Any:
    """Add a custom field to a portfolio"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_custom_field_setting_for_portfolio(parsed_body, portfolio)


@portfolios_group.command("add-item-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio. If the method is called asynchronously, returns the request thread.")
@click.option("--body", required=True, help="Information about the item being inserted.")
@formatted
def add_item_for_portfolio(portfolio: str, body: str) -> Any:
    """Add a portfolio item"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_item_for_portfolio(parsed_body, portfolio)


@portfolios_group.command("add-members-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio.")
@click.option("--body", required=True, help="Information about the members being added.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_members_for_portfolio(portfolio: str, body: str, opt_fields: str | None) -> Any:
    """Add users to a portfolio"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_members_for_portfolio(parsed_body, portfolio, opts)


@portfolios_group.command("create-portfolio")
@click.option("--body", required=True, help="The portfolio to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_portfolio(body: str, opt_fields: str | None) -> Any:
    """Create a portfolio"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_portfolio(parsed_body, opts)


@portfolios_group.command("delete-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_portfolio(portfolio: str) -> Any:
    """Delete a portfolio"""
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_portfolio(portfolio)


@portfolios_group.command("duplicate-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def duplicate_portfolio(portfolio: str, opt_fields: str | None) -> Any:
    """Duplicate a portfolio"""
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.duplicate_portfolio(portfolio, opts)


@portfolios_group.command("get-items-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_items_for_portfolio(portfolio: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get portfolio items"""
    session = AsanaSession.from_env(paginate=paginate)
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_items_for_portfolio(portfolio, opts)


@portfolios_group.command("get-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_portfolio(portfolio: str, opt_fields: str | None) -> Any:
    """Get a portfolio"""
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_portfolio(portfolio, opts)


@portfolios_group.command("get-portfolios")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--owner", default=None, help="The user who owns the portfolio. Currently, API users can only get a list of portfolios that they themselves own, unless the request is made from a Service Account. In the case of a Service Account...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_portfolios(workspace: str | None, limit: int | None, offset: str | None, opt_fields: str | None, owner: str | None, paginate: bool) -> Any:
    """Get multiple portfolios"""
    resolved_workspace = resolve_workspace(workspace, required=True)
    session = AsanaSession.from_env(paginate=paginate)
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if owner is not None:
        opts["owner"] = owner
    return api.get_portfolios(resolved_workspace, opts)


@portfolios_group.command("remove-custom-field-setting-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio. If the method is called asynchronously, returns the request thread.")
@click.option("--body", required=True, help="Information about the custom field setting being removed.")
@formatted
def remove_custom_field_setting_for_portfolio(portfolio: str, body: str) -> Any:
    """Remove a custom field from a portfolio"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_custom_field_setting_for_portfolio(parsed_body, portfolio)


@portfolios_group.command("remove-item-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio. If the method is called asynchronously, returns the request thread.")
@click.option("--body", required=True, help="Information about the item being removed.")
@formatted
def remove_item_for_portfolio(portfolio: str, body: str) -> Any:
    """Remove a portfolio item"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_item_for_portfolio(parsed_body, portfolio)


@portfolios_group.command("remove-members-for-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio.")
@click.option("--body", required=True, help="Information about the members being removed.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def remove_members_for_portfolio(portfolio: str, body: str, opt_fields: str | None) -> Any:
    """Remove users from a portfolio"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.remove_members_for_portfolio(parsed_body, portfolio, opts)


@portfolios_group.command("update-portfolio")
@click.option("--portfolio", required=True, help="Globally unique identifier for the portfolio.")
@click.option("--body", required=True, help="The updated fields for the portfolio.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_portfolio(portfolio: str, body: str, opt_fields: str | None) -> Any:
    """Update a portfolio"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = PortfoliosApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_portfolio(parsed_body, portfolio, opts)
