# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import ProjectBriefsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("project-briefs")
def project_briefs_group() -> None:
    """ProjectBriefs commands."""


@project_briefs_group.command("create-project-brief")
@click.argument("project_gid")
@click.option("--body", required=True, help="The project brief to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_project_brief(project_gid: str, body: str, opt_fields: str | None) -> Any:
    """Create a project brief"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectBriefsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_project_brief(parsed_body, project_gid, opts)


@project_briefs_group.command("delete-project-brief")
@click.argument("project_brief_gid")
@formatted
def delete_project_brief(project_brief_gid: str) -> Any:
    """Delete a project brief"""
    session = AsanaSession.from_env()
    api = ProjectBriefsApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_project_brief(project_brief_gid)


@project_briefs_group.command("get-project-brief")
@click.argument("project_brief_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_project_brief(project_brief_gid: str, opt_fields: str | None) -> Any:
    """Get a project brief"""
    session = AsanaSession.from_env()
    api = ProjectBriefsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_project_brief(project_brief_gid, opts)


@project_briefs_group.command("update-project-brief")
@click.argument("project_brief_gid")
@click.option("--body", required=True, help="The updated fields for the project brief.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_project_brief(project_brief_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a project brief"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectBriefsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_project_brief(parsed_body, project_brief_gid, opts)
