# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import ProjectTemplatesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("project-templates")
def project_templates_group() -> None:
    """ProjectTemplates commands."""


@project_templates_group.command("delete-project-template")
@click.argument("project_template_gid")
@formatted
def delete_project_template(project_template_gid: str) -> Any:
    """Delete a project template"""
    session = AsanaSession.from_env()
    api = ProjectTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_project_template(project_template_gid)


@project_templates_group.command("get-project-template")
@click.argument("project_template_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_project_template(project_template_gid: str, opt_fields: str | None) -> Any:
    """Get a project template"""
    session = AsanaSession.from_env()
    api = ProjectTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_project_template(project_template_gid, opts)


@project_templates_group.command("get-project-templates")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--team", default=None, help="The team to filter projects on.")
@click.option("--workspace", default=None, help="The workspace to filter results on.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_project_templates(limit: int | None, offset: str | None, opt_fields: str | None, team: str | None, workspace: str | None, paginate: bool) -> Any:
    """Get multiple project templates"""
    session = AsanaSession.from_env(paginate=paginate)
    api = ProjectTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if team is not None:
        opts["team"] = team
    if workspace is not None:
        opts["workspace"] = workspace
    return api.get_project_templates(opts)


@project_templates_group.command("get-project-templates-for-team")
@click.argument("team_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_project_templates_for_team(team_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get a team's project templates"""
    session = AsanaSession.from_env(paginate=paginate)
    api = ProjectTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_project_templates_for_team(team_gid, opts)


@project_templates_group.command("instantiate-project")
@click.argument("project_template_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def instantiate_project(project_template_gid: str, opt_fields: str | None) -> Any:
    """Instantiate a project from a project template"""
    session = AsanaSession.from_env()
    api = ProjectTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.instantiate_project(project_template_gid, opts)
