# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import ProjectStatusesApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("project-statuses", cls=GroupWithGlobalOptions)
def project_statuses_group() -> None:
    """ProjectStatuses commands."""


@project_statuses_group.command("create-project-status-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="The project status to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_project_status_for_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Create a project status"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_project_status_for_project(parsed_body, project, opts)


@project_statuses_group.command("delete-project-status")
@click.option("--project-status", required=True, help="The project status update to get. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_project_status(project_status: str) -> Any:
    """Delete a project status"""
    session = AsanaSession.from_env()
    api = ProjectStatusesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_project_status(project_status)


@project_statuses_group.command("get-project-status")
@click.option("--project-status", required=True, help="The project status update to get.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_project_status(project_status: str, opt_fields: str | None) -> Any:
    """Get a project status"""
    session = AsanaSession.from_env()
    api = ProjectStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_project_status(project_status, opts)


@project_statuses_group.command("get-project-statuses-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_project_statuses_for_project(project: str, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get statuses from a project"""
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = ProjectStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_project_statuses_for_project, project, opts=opts, max_items=max_items)
    return api.get_project_statuses_for_project(project, opts)
