# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import ProjectsApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("projects", cls=GroupWithGlobalOptions)
def projects_group() -> None:
    """Projects commands."""


@projects_group.command("add-custom-field-setting-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="Information about the custom field setting.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_custom_field_setting_for_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Add a custom field to a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_custom_field_setting_for_project(parsed_body, project, opts)


@projects_group.command("add-followers-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="Information about the followers being added.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_followers_for_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Add followers to a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_followers_for_project(parsed_body, project, opts)


@projects_group.command("add-members-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="Information about the members being added.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_members_for_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Add users to a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_members_for_project(parsed_body, project, opts)


@projects_group.command("create-project")
@click.option("--body", required=True, help="The project to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_project(body: str, opt_fields: str | None) -> Any:
    """Create a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_project(parsed_body, opts)


@projects_group.command("create-project-for-team")
@click.option("--team", required=True, help="Globally unique identifier for the team.")
@click.option("--body", required=True, help="The new project to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_project_for_team(team: str, body: str, opt_fields: str | None) -> Any:
    """Create a project in a team"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_project_for_team(parsed_body, team, opts)


@projects_group.command("create-project-for-workspace")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--body", required=True, help="The new project to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_project_for_workspace(workspace: str | None, body: str, opt_fields: str | None) -> Any:
    """Create a project in a workspace"""
    parsed_body = resolve_body(body)
    resolved_workspace = resolve_workspace(workspace, required=True)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_project_for_workspace(parsed_body, resolved_workspace, opts)


@projects_group.command("delete-project")
@click.option("--project", required=True, help="Globally unique identifier for the project. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_project(project: str) -> Any:
    """Delete a project"""
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_project(project)


@projects_group.command("duplicate-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def duplicate_project(project: str, opt_fields: str | None) -> Any:
    """Duplicate a project"""
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.duplicate_project(project, opts)


@projects_group.command("get-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_project(project: str, opt_fields: str | None) -> Any:
    """Get a project"""
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_project(project, opts)


@projects_group.command("get-projects")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--archived", type=bool, default=None, help="Only return projects whose `archived` field takes on the value of this parameter.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--team", default=None, help="**Deprecated.** The team to filter projects on. Please use `GET /memberships` with `{ member: team, resource_subtype: project_membership }` instead.")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_projects(workspace: str | None, archived: bool | None, offset: str | None, opt_fields: str | None, team: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get multiple projects"""
    resolved_workspace = resolve_workspace(workspace, required=False)
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if archived is not None:
        opts["archived"] = archived
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if team is not None:
        opts["team"] = team
    if resolved_workspace is not None:
        opts["workspace"] = resolved_workspace
    if max_items is not None:
        return session.fetch_capped(api.get_projects, opts=opts, max_items=max_items)
    return api.get_projects(opts)


@projects_group.command("get-projects-for-task")
@click.option("--task", required=True, help="The task to operate on.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_projects_for_task(task: str, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get projects a task is in"""
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_projects_for_task, task, opts=opts, max_items=max_items)
    return api.get_projects_for_task(task, opts)


@projects_group.command("get-projects-for-team")
@click.option("--team", required=True, help="Globally unique identifier for the team.")
@click.option("--archived", type=bool, default=None, help="Only return projects whose `archived` field takes on the value of this parameter.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_projects_for_team(team: str, archived: bool | None, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get a team's projects"""
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if archived is not None:
        opts["archived"] = archived
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_projects_for_team, team, opts=opts, max_items=max_items)
    return api.get_projects_for_team(team, opts)


@projects_group.command("get-projects-for-workspace")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--archived", type=bool, default=None, help="Only return projects whose `archived` field takes on the value of this parameter.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_projects_for_workspace(workspace: str | None, archived: bool | None, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get all projects in a workspace"""
    resolved_workspace = resolve_workspace(workspace, required=True)
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if archived is not None:
        opts["archived"] = archived
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_projects_for_workspace, resolved_workspace, opts=opts, max_items=max_items)
    return api.get_projects_for_workspace(resolved_workspace, opts)


@projects_group.command("get-task-counts-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_task_counts_for_project(project: str, opt_fields: str | None) -> Any:
    """Get task count of a project"""
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_task_counts_for_project(project, opts)


@projects_group.command("project-save-as-template")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="Describes the inputs used for creating a project template, such as the resulting project template's name, which team it should be created in.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def project_save_as_template(project: str, body: str, opt_fields: str | None) -> Any:
    """Create a project template from a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.project_save_as_template(parsed_body, project, opts)


@projects_group.command("remove-custom-field-setting-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project. If the method is called asynchronously, returns the request thread.")
@click.option("--body", required=True, help="Information about the custom field setting being removed.")
@formatted
def remove_custom_field_setting_for_project(project: str, body: str) -> Any:
    """Remove a custom field from a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_custom_field_setting_for_project(parsed_body, project)


@projects_group.command("remove-followers-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="Information about the followers being removed.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def remove_followers_for_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Remove followers from a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.remove_followers_for_project(parsed_body, project, opts)


@projects_group.command("remove-members-for-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="Information about the members being removed.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def remove_members_for_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Remove users from a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.remove_members_for_project(parsed_body, project, opts)


@projects_group.command("search-projects-for-workspace")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--completed", type=bool, default=None, help="Filter on project completion status.")
@click.option("--completed-on", default=None, help="ISO 8601 date string or `null`.")
@click.option("--created-on", default=None, help="ISO 8601 date string or `null`.")
@click.option("--due-on", default=None, help="ISO 8601 date string or `null`.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--sort-ascending", type=bool, default=None, help="Default `false`.")
@click.option("--sort-by", default=None, help="One of `due_date`, `created_at`, `completed_at`, or `modified_at`, defaults to `modified_at`.")
@click.option("--start-on", default=None, help="ISO 8601 date string or `null`.")
@click.option("--text", default=None, help="Performs full-text search on the project name.")
@formatted
def search_projects_for_workspace(workspace: str | None, completed: bool | None, completed_on: str | None, created_on: str | None, due_on: str | None, opt_fields: str | None, sort_ascending: bool | None, sort_by: str | None, start_on: str | None, text: str | None) -> Any:
    """Search projects in a workspace"""
    resolved_workspace = resolve_workspace(workspace, required=True)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if completed is not None:
        opts["completed"] = completed
    if completed_on is not None:
        opts["completed_on"] = completed_on
    if created_on is not None:
        opts["created_on"] = created_on
    if due_on is not None:
        opts["due_on"] = due_on
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if sort_ascending is not None:
        opts["sort_ascending"] = sort_ascending
    if sort_by is not None:
        opts["sort_by"] = sort_by
    if start_on is not None:
        opts["start_on"] = start_on
    if text is not None:
        opts["text"] = text
    return api.search_projects_for_workspace(resolved_workspace, opts)


@projects_group.command("update-project")
@click.option("--project", required=True, help="Globally unique identifier for the project.")
@click.option("--body", required=True, help="The updated fields for the project.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_project(project: str, body: str, opt_fields: str | None) -> Any:
    """Update a project"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = ProjectsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_project(parsed_body, project, opts)
