# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import RatesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("rates")
def rates_group() -> None:
    """Rates commands."""


@rates_group.command("create-rate")
@click.option("--body", required=True, help="The rate to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_rate(body: str, opt_fields: str | None) -> Any:
    """Create a rate"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_rate(parsed_body, opts)


@rates_group.command("delete-rate")
@click.option("--rate", required=True, help="Globally unique identifier for the rate. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_rate(rate: str) -> Any:
    """Delete a rate"""
    session = AsanaSession.from_env()
    api = RatesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_rate(rate)


@rates_group.command("get-rate")
@click.option("--rate", required=True, help="Globally unique identifier for the rate.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_rate(rate: str, opt_fields: str | None) -> Any:
    """Get a rate"""
    session = AsanaSession.from_env()
    api = RatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_rate(rate, opts)


@rates_group.command("get-rates")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--parent", default=None, help="Globally unique identifier for `project`.")
@click.option("--resource", default=None, help="Globally unique identifier for `user` or `placeholder`.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_rates(limit: int | None, offset: str | None, opt_fields: str | None, parent: str | None, resource: str | None, paginate: bool) -> Any:
    """Get multiple rates"""
    session = AsanaSession.from_env(paginate=paginate)
    api = RatesApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if parent is not None:
        opts["parent"] = parent
    if resource is not None:
        opts["resource"] = resource
    return api.get_rates(opts)


@rates_group.command("update-rate")
@click.option("--rate", required=True, help="Globally unique identifier for the rate.")
@click.option("--body", required=True, help="The updated fields for the rate.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_rate(rate: str, body: str, opt_fields: str | None) -> Any:
    """Update a rate"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_rate(parsed_body, rate, opts)
