# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import RolesApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("roles", cls=GroupWithGlobalOptions)
def roles_group() -> None:
    """Roles commands."""


@roles_group.command("create-role")
@click.option("--body", required=True, help="The role to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_role(body: str, opt_fields: str | None) -> Any:
    """Create a role"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_role(parsed_body, opts)


@roles_group.command("delete-role")
@click.option("--role", required=True, help="Globally unique identifier for the role. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_role(role: str) -> Any:
    """Delete a role"""
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_role(role)


@roles_group.command("get-role")
@click.option("--role", required=True, help="Globally unique identifier for the role.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_role(role: str, opt_fields: str | None) -> Any:
    """Get a role"""
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_role(role, opts)


@roles_group.command("get-roles")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--archived", type=bool, default=None, help="Only return projects whose `archived` field takes on the value of this parameter.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_roles(workspace: str | None, archived: bool | None, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get multiple roles"""
    resolved_workspace = resolve_workspace(workspace, required=False)
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if archived is not None:
        opts["archived"] = archived
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if resolved_workspace is not None:
        opts["workspace"] = resolved_workspace
    if max_items is not None:
        return session.fetch_capped(api.get_roles, opts=opts, max_items=max_items)
    return api.get_roles(opts)


@roles_group.command("update-role")
@click.option("--role", required=True, help="Globally unique identifier for the role.")
@click.option("--body", required=True, help="The updated fields for the role.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_role(role: str, body: str, opt_fields: str | None) -> Any:
    """Update a role"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_role(parsed_body, role, opts)
