# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import RolesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("roles")
def roles_group() -> None:
    """Roles commands."""


@roles_group.command("create-role")
@click.option("--body", required=True, help="The role to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_role(body: str, opt_fields: str | None) -> Any:
    """Create a role"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_role(parsed_body, opts)


@roles_group.command("delete-role")
@click.argument("role_gid")
@formatted
def delete_role(role_gid: str) -> Any:
    """Delete a role"""
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_role(role_gid)


@roles_group.command("get-role")
@click.argument("role_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_role(role_gid: str, opt_fields: str | None) -> Any:
    """Get a role"""
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_role(role_gid, opts)


@roles_group.command("get-roles")
@click.option("--archived", type=bool, default=None, help="Only return projects whose `archived` field takes on the value of this parameter.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--workspace", default=None, help="The workspace or organization to filter roles on.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_roles(archived: bool | None, limit: int | None, offset: str | None, opt_fields: str | None, workspace: str | None, paginate: bool) -> Any:
    """Get multiple roles"""
    session = AsanaSession.from_env(paginate=paginate)
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if archived is not None:
        opts["archived"] = archived
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if workspace is not None:
        opts["workspace"] = workspace
    return api.get_roles(opts)


@roles_group.command("update-role")
@click.argument("role_gid")
@click.option("--body", required=True, help="The updated fields for the role.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_role(role_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a role"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RolesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_role(parsed_body, role_gid, opts)
