# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import RulesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("rules")
def rules_group() -> None:
    """Rules commands."""


@rules_group.command("trigger-rule")
@click.argument("rule_trigger_gid")
@click.option("--body", required=True, help="A dictionary of variables accessible from within the rule.")
@formatted
def trigger_rule(rule_trigger_gid: str, body: str) -> Any:
    """Trigger a rule"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = RulesApi(session.client)
    opts: dict[str, Any] = {}
    return api.trigger_rule(parsed_body, rule_trigger_gid)
