# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import StatusUpdatesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("status-updates")
def status_updates_group() -> None:
    """StatusUpdates commands."""


@status_updates_group.command("create-status-for-object")
@click.option("--body", required=True, help="The status update to create.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def create_status_for_object(body: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Create a status update"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env(paginate=paginate)
    api = StatusUpdatesApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_status_for_object(parsed_body, opts)


@status_updates_group.command("delete-status")
@click.argument("status_update_gid")
@formatted
def delete_status(status_update_gid: str) -> Any:
    """Delete a status update"""
    session = AsanaSession.from_env()
    api = StatusUpdatesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_status(status_update_gid)


@status_updates_group.command("get-status")
@click.argument("status_update_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_status(status_update_gid: str, opt_fields: str | None) -> Any:
    """Get a status update"""
    session = AsanaSession.from_env()
    api = StatusUpdatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_status(status_update_gid, opts)


@status_updates_group.command("get-statuses-for-object")
@click.argument("parent")
@click.option("--created-since", default=None, help="Only return statuses that have been created since the given time.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_statuses_for_object(parent: str, created_since: str | None, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get status updates from an object"""
    session = AsanaSession.from_env(paginate=paginate)
    api = StatusUpdatesApi(session.client)
    opts: dict[str, Any] = {}
    if created_since is not None:
        opts["created_since"] = created_since
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_statuses_for_object(parent, opts)
