# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import TaskTemplatesApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("task-templates", cls=GroupWithGlobalOptions)
def task_templates_group() -> None:
    """TaskTemplates commands."""


@task_templates_group.command("delete-task-template")
@click.option("--task-template", required=True, help="Globally unique identifier for the task template. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_task_template(task_template: str) -> Any:
    """Delete a task template"""
    session = AsanaSession.from_env()
    api = TaskTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_task_template(task_template)


@task_templates_group.command("get-task-template")
@click.option("--task-template", required=True, help="Globally unique identifier for the task template.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_task_template(task_template: str, opt_fields: str | None) -> Any:
    """Get a task template"""
    session = AsanaSession.from_env()
    api = TaskTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_task_template(task_template, opts)


@task_templates_group.command("get-task-templates")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--project", default=None, help="The project to filter task templates on.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_task_templates(limit: int | None, offset: str | None, opt_fields: str | None, project: str | None, paginate: bool) -> Any:
    """Get multiple task templates"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TaskTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if project is not None:
        opts["project"] = project
    return api.get_task_templates(opts)


@task_templates_group.command("instantiate-task")
@click.option("--task-template", required=True, help="Globally unique identifier for the task template.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def instantiate_task(task_template: str, opt_fields: str | None) -> Any:
    """Instantiate a task from a task template"""
    session = AsanaSession.from_env()
    api = TaskTemplatesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.instantiate_task(task_template, opts)
