# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import TasksApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("tasks")
def tasks_group() -> None:
    """Tasks commands."""


@tasks_group.command("add-dependencies-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The list of tasks to set as dependencies.")
@formatted
def add_dependencies_for_task(task_gid: str, body: str) -> Any:
    """Set dependencies for a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_dependencies_for_task(parsed_body, task_gid)


@tasks_group.command("add-dependents-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The list of tasks to add as dependents.")
@formatted
def add_dependents_for_task(task_gid: str, body: str) -> Any:
    """Set dependents for a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_dependents_for_task(parsed_body, task_gid)


@tasks_group.command("add-followers-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The followers to add to the task.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_followers_for_task(task_gid: str, body: str, opt_fields: str | None) -> Any:
    """Add followers to a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_followers_for_task(parsed_body, task_gid, opts)


@tasks_group.command("add-project-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The project to add the task to.")
@formatted
def add_project_for_task(task_gid: str, body: str) -> Any:
    """Add a project to a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_project_for_task(parsed_body, task_gid)


@tasks_group.command("add-tag-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The tag to add to the task.")
@formatted
def add_tag_for_task(task_gid: str, body: str) -> Any:
    """Add a tag to a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.add_tag_for_task(parsed_body, task_gid)


@tasks_group.command("create-subtask-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The new subtask to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_subtask_for_task(task_gid: str, body: str, opt_fields: str | None) -> Any:
    """Create a subtask"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_subtask_for_task(parsed_body, task_gid, opts)


@tasks_group.command("create-task")
@click.option("--body", required=True, help="The task to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_task(body: str, opt_fields: str | None) -> Any:
    """Create a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_task(parsed_body, opts)


@tasks_group.command("delete-task")
@click.argument("task_gid")
@formatted
def delete_task(task_gid: str) -> Any:
    """Delete a task"""
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_task(task_gid)


@tasks_group.command("duplicate-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="Describes the duplicate's name and the fields that will be duplicated.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def duplicate_task(task_gid: str, body: str, opt_fields: str | None) -> Any:
    """Duplicate a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.duplicate_task(parsed_body, task_gid, opts)


@tasks_group.command("get-dependencies-for-task")
@click.argument("task_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_dependencies_for_task(task_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get dependencies from a task"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_dependencies_for_task(task_gid, opts)


@tasks_group.command("get-dependents-for-task")
@click.argument("task_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_dependents_for_task(task_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get dependents from a task"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_dependents_for_task(task_gid, opts)


@tasks_group.command("get-subtasks-for-task")
@click.argument("task_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_subtasks_for_task(task_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get subtasks from a task"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_subtasks_for_task(task_gid, opts)


@tasks_group.command("get-task")
@click.argument("task_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_task(task_gid: str, opt_fields: str | None) -> Any:
    """Get a task"""
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_task(task_gid, opts)


@tasks_group.command("get-task-for-custom-id")
@click.argument("workspace_gid")
@click.argument("custom_id")
@formatted
def get_task_for_custom_id(workspace_gid: str, custom_id: str) -> Any:
    """Get a task for a given custom ID"""
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.get_task_for_custom_id(workspace_gid, custom_id)


@tasks_group.command("get-tasks")
@click.option("--assignee", default=None, help="The assignee to filter tasks on. If searching for unassigned tasks, assignee.any = null can be specified. *Note: If you specify `assignee`, you must also specify the `workspace` to filter on.*")
@click.option("--completed-since", default=None, help="Only return tasks that are either incomplete or that have been completed since this time.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--modified-since", default=None, help="Only return tasks that have been modified since the given time. *Note: A task is considered “modified” if any of its properties change, or associations between it and other objects are modified (e....")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--project", default=None, help="The project to filter tasks on.")
@click.option("--section", default=None, help="The section to filter tasks on.")
@click.option("--workspace", default=None, help="The workspace to filter tasks on. *Note: If you specify `workspace`, you must also specify the `assignee` to filter on.*")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_tasks(assignee: str | None, completed_since: str | None, limit: int | None, modified_since: str | None, offset: str | None, opt_fields: str | None, project: str | None, section: str | None, workspace: str | None, paginate: bool) -> Any:
    """Get multiple tasks"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if assignee is not None:
        opts["assignee"] = assignee
    if completed_since is not None:
        opts["completed_since"] = completed_since
    if limit is not None:
        opts["limit"] = limit
    if modified_since is not None:
        opts["modified_since"] = modified_since
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if project is not None:
        opts["project"] = project
    if section is not None:
        opts["section"] = section
    if workspace is not None:
        opts["workspace"] = workspace
    return api.get_tasks(opts)


@tasks_group.command("get-tasks-for-project")
@click.argument("project_gid")
@click.option("--completed-since", default=None, help="Only return tasks that are either incomplete or that have been completed since this time. Accepts a date-time string or the keyword *now*.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_tasks_for_project(project_gid: str, completed_since: str | None, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get tasks from a project"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if completed_since is not None:
        opts["completed_since"] = completed_since
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_tasks_for_project(project_gid, opts)


@tasks_group.command("get-tasks-for-section")
@click.argument("section_gid")
@click.option("--completed-since", default=None, help="Only return tasks that are either incomplete or that have been completed since this time. Accepts a date-time string or the keyword *now*.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_tasks_for_section(section_gid: str, completed_since: str | None, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get tasks from a section"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if completed_since is not None:
        opts["completed_since"] = completed_since
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_tasks_for_section(section_gid, opts)


@tasks_group.command("get-tasks-for-tag")
@click.argument("tag_gid")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_tasks_for_tag(tag_gid: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get tasks from a tag"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_tasks_for_tag(tag_gid, opts)


@tasks_group.command("get-tasks-for-user-task-list")
@click.argument("user_task_list_gid")
@click.option("--completed-since", default=None, help="Only return tasks that are either incomplete or that have been completed since this time. Accepts a date-time string or the keyword *now*.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_tasks_for_user_task_list(user_task_list_gid: str, completed_since: str | None, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get tasks from a user task list"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if completed_since is not None:
        opts["completed_since"] = completed_since
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_tasks_for_user_task_list(user_task_list_gid, opts)


@tasks_group.command("remove-dependencies-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The list of tasks to unlink as dependencies.")
@formatted
def remove_dependencies_for_task(task_gid: str, body: str) -> Any:
    """Unlink dependencies from a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_dependencies_for_task(parsed_body, task_gid)


@tasks_group.command("remove-dependents-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The list of tasks to remove as dependents.")
@formatted
def remove_dependents_for_task(task_gid: str, body: str) -> Any:
    """Unlink dependents from a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_dependents_for_task(parsed_body, task_gid)


@tasks_group.command("remove-follower-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The followers to remove from the task.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def remove_follower_for_task(task_gid: str, body: str, opt_fields: str | None) -> Any:
    """Remove followers from a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.remove_follower_for_task(parsed_body, task_gid, opts)


@tasks_group.command("remove-project-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The project to remove the task from.")
@formatted
def remove_project_for_task(task_gid: str, body: str) -> Any:
    """Remove a project from a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_project_for_task(parsed_body, task_gid)


@tasks_group.command("remove-tag-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The tag to remove from the task.")
@formatted
def remove_tag_for_task(task_gid: str, body: str) -> Any:
    """Remove a tag from a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_tag_for_task(parsed_body, task_gid)


@tasks_group.command("search-tasks-for-workspace")
@click.argument("workspace_gid")
@click.option("--completed", type=bool, default=None, help="Filter to completed tasks")
@click.option("--completed-on", default=None, help="ISO 8601 date string or `null`")
@click.option("--created-on", default=None, help="ISO 8601 date string or `null`")
@click.option("--due-on", default=None, help="ISO 8601 date string or `null`")
@click.option("--has-attachment", type=bool, default=None, help="Filter to tasks with attachments")
@click.option("--is-blocked", type=bool, default=None, help="Filter to tasks with incomplete dependencies")
@click.option("--is-blocking", type=bool, default=None, help="Filter to incomplete tasks with dependents")
@click.option("--is-subtask", type=bool, default=None, help="Filter to subtasks")
@click.option("--modified-on", default=None, help="ISO 8601 date string or `null`")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--resource-subtype", default=None, help="Filters results by the task's resource_subtype")
@click.option("--sort-ascending", type=bool, default=None, help="Default `false`")
@click.option("--sort-by", default=None, help="One of `due_date`, `created_at`, `completed_at`, `likes`, or `modified_at`, defaults to `modified_at`")
@click.option("--start-on", default=None, help="ISO 8601 date string or `null`")
@click.option("--text", default=None, help="Performs full-text search on both task name and description")
@formatted
def search_tasks_for_workspace(workspace_gid: str, completed: bool | None, completed_on: str | None, created_on: str | None, due_on: str | None, has_attachment: bool | None, is_blocked: bool | None, is_blocking: bool | None, is_subtask: bool | None, modified_on: str | None, opt_fields: str | None, resource_subtype: str | None, sort_ascending: bool | None, sort_by: str | None, start_on: str | None, text: str | None) -> Any:
    """Search tasks in a workspace"""
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if completed is not None:
        opts["completed"] = completed
    if completed_on is not None:
        opts["completed_on"] = completed_on
    if created_on is not None:
        opts["created_on"] = created_on
    if due_on is not None:
        opts["due_on"] = due_on
    if has_attachment is not None:
        opts["has_attachment"] = has_attachment
    if is_blocked is not None:
        opts["is_blocked"] = is_blocked
    if is_blocking is not None:
        opts["is_blocking"] = is_blocking
    if is_subtask is not None:
        opts["is_subtask"] = is_subtask
    if modified_on is not None:
        opts["modified_on"] = modified_on
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if resource_subtype is not None:
        opts["resource_subtype"] = resource_subtype
    if sort_ascending is not None:
        opts["sort_ascending"] = sort_ascending
    if sort_by is not None:
        opts["sort_by"] = sort_by
    if start_on is not None:
        opts["start_on"] = start_on
    if text is not None:
        opts["text"] = text
    return api.search_tasks_for_workspace(workspace_gid, opts)


@tasks_group.command("set-parent-for-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The new parent of the subtask.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def set_parent_for_task(task_gid: str, body: str, opt_fields: str | None) -> Any:
    """Set the parent of a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.set_parent_for_task(parsed_body, task_gid, opts)


@tasks_group.command("update-task")
@click.argument("task_gid")
@click.option("--body", required=True, help="The task to update.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_task(task_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a task"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TasksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_task(parsed_body, task_gid, opts)
