# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import TeamsApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("teams", cls=GroupWithGlobalOptions)
def teams_group() -> None:
    """Teams commands."""


@teams_group.command("add-user-for-team")
@click.option("--team", required=True, help="Globally unique identifier for the team.")
@click.option("--body", required=True, help="The user to add to the team.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_user_for_team(team: str, body: str, opt_fields: str | None) -> Any:
    """Add a user to a team"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_user_for_team(parsed_body, team, opts)


@teams_group.command("create-team")
@click.option("--body", required=True, help="The team to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_team(body: str, opt_fields: str | None) -> Any:
    """Create a team"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_team(parsed_body, opts)


@teams_group.command("get-team")
@click.option("--team", required=True, help="Globally unique identifier for the team.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_team(team: str, opt_fields: str | None) -> Any:
    """Get a team"""
    session = AsanaSession.from_env()
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_team(team, opts)


@teams_group.command("get-teams-for-user")
@click.option("--user", required=True, help="A string identifying a user. This can either be the string \"me\", an email, or the gid of a user.")
@click.option("--organization", required=True, help="The workspace or organization to filter teams on.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_teams_for_user(user: str, organization: str, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get teams for a user"""
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_teams_for_user, user, organization, opts=opts, max_items=max_items)
    return api.get_teams_for_user(user, organization, opts)


@teams_group.command("get-teams-for-workspace")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_teams_for_workspace(workspace: str | None, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get teams in a workspace"""
    resolved_workspace = resolve_workspace(workspace, required=True)
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_teams_for_workspace, resolved_workspace, opts=opts, max_items=max_items)
    return api.get_teams_for_workspace(resolved_workspace, opts)


@teams_group.command("remove-user-for-team")
@click.option("--team", required=True, help="Globally unique identifier for the team. If the method is called asynchronously, returns the request thread.")
@click.option("--body", required=True, help="The user to remove from the team.")
@formatted
def remove_user_for_team(team: str, body: str) -> Any:
    """Remove a user from a team"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_user_for_team(parsed_body, team)


@teams_group.command("update-team")
@click.option("--team", required=True, help="Globally unique identifier for the team.")
@click.option("--body", required=True, help="The team to update.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_team(team: str, body: str, opt_fields: str | None) -> Any:
    """Update a team"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TeamsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_team(parsed_body, team, opts)
