# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import TimesheetApprovalStatusesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("timesheet-approval-statuses")
def timesheet_approval_statuses_group() -> None:
    """TimesheetApprovalStatuses commands."""


@timesheet_approval_statuses_group.command("create-timesheet-approval-status")
@click.option("--body", required=True, help="The timesheet approval status to create.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_timesheet_approval_status(body: str, opt_fields: str | None) -> Any:
    """Create a timesheet approval status"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = TimesheetApprovalStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_timesheet_approval_status(parsed_body, opts)


@timesheet_approval_statuses_group.command("get-timesheet-approval-status")
@click.argument("timesheet_approval_status_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_timesheet_approval_status(timesheet_approval_status_gid: str, opt_fields: str | None) -> Any:
    """Get a timesheet approval status"""
    session = AsanaSession.from_env()
    api = TimesheetApprovalStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_timesheet_approval_status(timesheet_approval_status_gid, opts)


@timesheet_approval_statuses_group.command("get-timesheet-approval-statuses")
@click.argument("workspace")
@click.option("--approval-statuses", default=None, help="Filter by approval status. Can be one or more of draft, submitted, approved, or rejected.")
@click.option("--from-date", default=None, help="The start date for filtering timesheet approval statuses.")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--to-date", default=None, help="The end date for filtering timesheet approval statuses.")
@click.option("--user", default=None, help="Globally unique identifier for the user to filter timesheet approval statuses by.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_timesheet_approval_statuses(workspace: str, approval_statuses: str | None, from_date: str | None, limit: int | None, offset: str | None, opt_fields: str | None, to_date: str | None, user: str | None, paginate: bool) -> Any:
    """Get multiple timesheet approval statuses"""
    session = AsanaSession.from_env(paginate=paginate)
    api = TimesheetApprovalStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if approval_statuses is not None:
        opts["approval_statuses"] = approval_statuses
    if from_date is not None:
        opts["from_date"] = from_date
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if to_date is not None:
        opts["to_date"] = to_date
    if user is not None:
        opts["user"] = user
    return api.get_timesheet_approval_statuses(workspace, opts)


@timesheet_approval_statuses_group.command("update-timesheet-approval-status")
@click.argument("timesheet_approval_status_gid")
@click.option("--body", required=True, help="The fields to update on the timesheet approval status.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_timesheet_approval_status(timesheet_approval_status_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a timesheet approval status"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = TimesheetApprovalStatusesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_timesheet_approval_status(parsed_body, timesheet_approval_status_gid, opts)
