# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import TimeTrackingEntriesApi

from asana_api_cli.click_ext import GroupWithGlobalOptions
from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("time-tracking-entries", cls=GroupWithGlobalOptions)
def time_tracking_entries_group() -> None:
    """TimeTrackingEntries commands."""


@time_tracking_entries_group.command("create-time-tracking-entry")
@click.option("--task", required=True, help="The task to operate on.")
@click.option("--body", required=True, help="Information about the time tracking entry.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_time_tracking_entry(task: str, body: str, opt_fields: str | None) -> Any:
    """Create a time tracking entry"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TimeTrackingEntriesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_time_tracking_entry(parsed_body, task, opts)


@time_tracking_entries_group.command("delete-time-tracking-entry")
@click.option("--time-tracking-entry", required=True, help="Globally unique identifier for the time tracking entry. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_time_tracking_entry(time_tracking_entry: str) -> Any:
    """Delete a time tracking entry"""
    session = AsanaSession.from_env()
    api = TimeTrackingEntriesApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_time_tracking_entry(time_tracking_entry)


@time_tracking_entries_group.command("get-time-tracking-entries")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--attributable-to", default=None, help="Globally unique identifier for the project the time tracking entries are attributed to.")
@click.option("--entered-on-end-date", default=None, help="The end date for filtering time tracking entries by when they were entered.")
@click.option("--entered-on-start-date", default=None, help="The start date for filtering time tracking entries by when they were entered.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--portfolio", default=None, help="Globally unique identifier for the portfolio to filter time tracking entries by.")
@click.option("--task", default=None, help="Globally unique identifier for the task to filter time tracking entries by.")
@click.option("--timesheet-approval-status", default=None, help="Globally unique identifier for the timesheet approval status to filter time tracking entries by.")
@click.option("--user", default=None, help="Globally unique identifier for the user to filter time tracking entries by.")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_time_tracking_entries(workspace: str | None, attributable_to: str | None, entered_on_end_date: str | None, entered_on_start_date: str | None, offset: str | None, opt_fields: str | None, portfolio: str | None, task: str | None, timesheet_approval_status: str | None, user: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get multiple time tracking entries"""
    resolved_workspace = resolve_workspace(workspace, required=False)
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = TimeTrackingEntriesApi(session.client)
    opts: dict[str, Any] = {}
    if attributable_to is not None:
        opts["attributable_to"] = attributable_to
    if entered_on_end_date is not None:
        opts["entered_on_end_date"] = entered_on_end_date
    if entered_on_start_date is not None:
        opts["entered_on_start_date"] = entered_on_start_date
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if portfolio is not None:
        opts["portfolio"] = portfolio
    if task is not None:
        opts["task"] = task
    if timesheet_approval_status is not None:
        opts["timesheet_approval_status"] = timesheet_approval_status
    if user is not None:
        opts["user"] = user
    if resolved_workspace is not None:
        opts["workspace"] = resolved_workspace
    if max_items is not None:
        return session.fetch_capped(api.get_time_tracking_entries, opts=opts, max_items=max_items)
    return api.get_time_tracking_entries(opts)


@time_tracking_entries_group.command("get-time-tracking-entries-for-task")
@click.option("--task", required=True, help="The task to operate on.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--all-items", "all_items", is_flag=True, default=False, help="Fetch all items (no cap)")
@click.option("--paginate", "paginate", is_flag=True, default=False, help="(Deprecated) Alias for --all-items")
@click.option("--page-size", "page_size", type=int, default=None, help="Items per page (Asana API requires 1-100, default 100)")
@click.option("--max-items", "max_items", type=int, default=None, help="Stop after fetching this many items in total")
@formatted
def get_time_tracking_entries_for_task(task: str, offset: str | None, opt_fields: str | None, all_items: bool, paginate: bool, page_size: int | None, max_items: int | None) -> Any:
    """Get time tracking entries for a task"""
    if paginate:
        click.echo("Warning: --paginate is deprecated; use --all-items instead.", err=True)
    fetch_all = all_items or paginate
    if fetch_all and max_items is not None:
        raise click.UsageError("--max-items cannot be combined with --all-items (or its deprecated alias --paginate)")
    effective_page_size = page_size
    if max_items is not None and (page_size is None or page_size > max_items):
        effective_page_size = max_items
    session = AsanaSession.from_env(paginate=fetch_all, page_size=effective_page_size)
    api = TimeTrackingEntriesApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if max_items is not None:
        return session.fetch_capped(api.get_time_tracking_entries_for_task, task, opts=opts, max_items=max_items)
    return api.get_time_tracking_entries_for_task(task, opts)


@time_tracking_entries_group.command("get-time-tracking-entry")
@click.option("--time-tracking-entry", required=True, help="Globally unique identifier for the time tracking entry.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_time_tracking_entry(time_tracking_entry: str, opt_fields: str | None) -> Any:
    """Get a time tracking entry"""
    session = AsanaSession.from_env()
    api = TimeTrackingEntriesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_time_tracking_entry(time_tracking_entry, opts)


@time_tracking_entries_group.command("update-time-tracking-entry")
@click.option("--time-tracking-entry", required=True, help="Globally unique identifier for the time tracking entry.")
@click.option("--body", required=True, help="The updated fields for the time tracking entry.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_time_tracking_entry(time_tracking_entry: str, body: str, opt_fields: str | None) -> Any:
    """Update a time tracking entry"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = TimeTrackingEntriesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_time_tracking_entry(parsed_body, time_tracking_entry, opts)
