# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import UserTaskListsApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("user-task-lists")
def user_task_lists_group() -> None:
    """UserTaskLists commands."""


@user_task_lists_group.command("get-user-task-list")
@click.argument("user_task_list_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_user_task_list(user_task_list_gid: str, opt_fields: str | None) -> Any:
    """Get a user task list"""
    session = AsanaSession.from_env()
    api = UserTaskListsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_user_task_list(user_task_list_gid, opts)


@user_task_lists_group.command("get-user-task-list-for-user")
@click.argument("user_gid")
@click.argument("workspace")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_user_task_list_for_user(user_gid: str, workspace: str, opt_fields: str | None) -> Any:
    """Get a user's task list"""
    session = AsanaSession.from_env()
    api = UserTaskListsApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_user_task_list_for_user(user_gid, workspace, opts)
