# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import UsersApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body


@click.group("users")
def users_group() -> None:
    """Users commands."""


@users_group.command("get-favorites-for-user")
@click.argument("user_gid")
@click.argument("resource_type")
@click.argument("workspace")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_favorites_for_user(user_gid: str, resource_type: str, workspace: str, limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get a user's favorites"""
    session = AsanaSession.from_env(paginate=paginate)
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_favorites_for_user(user_gid, resource_type, workspace, opts)


@users_group.command("get-user")
@click.argument("user_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--workspace", default=None, help="The workspace to filter results on.")
@formatted
def get_user(user_gid: str, opt_fields: str | None, workspace: str | None) -> Any:
    """Get a user"""
    session = AsanaSession.from_env()
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if workspace is not None:
        opts["workspace"] = workspace
    return api.get_user(user_gid, opts)


@users_group.command("get-user-for-workspace")
@click.argument("workspace_gid")
@click.argument("user_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_user_for_workspace(workspace_gid: str, user_gid: str, opt_fields: str | None) -> Any:
    """Get a user in a workspace or organization"""
    session = AsanaSession.from_env()
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_user_for_workspace(workspace_gid, user_gid, opts)


@users_group.command("get-users")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--team", default=None, help="The team ID to filter users on.")
@click.option("--workspace", default=None, help="The workspace or organization ID to filter users on.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_users(limit: int | None, offset: str | None, opt_fields: str | None, team: str | None, workspace: str | None, paginate: bool) -> Any:
    """Get multiple users"""
    session = AsanaSession.from_env(paginate=paginate)
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if team is not None:
        opts["team"] = team
    if workspace is not None:
        opts["workspace"] = workspace
    return api.get_users(opts)


@users_group.command("get-users-for-team")
@click.argument("team_gid")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_users_for_team(team_gid: str, offset: str | None, opt_fields: str | None) -> Any:
    """Get users in a team"""
    session = AsanaSession.from_env()
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_users_for_team(team_gid, opts)


@users_group.command("get-users-for-workspace")
@click.argument("workspace_gid")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_users_for_workspace(workspace_gid: str, offset: str | None, opt_fields: str | None) -> Any:
    """Get users in a workspace or organization"""
    session = AsanaSession.from_env()
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_users_for_workspace(workspace_gid, opts)


@users_group.command("update-user")
@click.argument("user_gid")
@click.option("--body", required=True, help="The user to update.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--workspace", default=None, help="The workspace to filter results on.")
@formatted
def update_user(user_gid: str, body: str, opt_fields: str | None, workspace: str | None) -> Any:
    """Update a user"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if workspace is not None:
        opts["workspace"] = workspace
    return api.update_user(parsed_body, user_gid, opts)


@users_group.command("update-user-for-workspace")
@click.argument("workspace_gid")
@click.argument("user_gid")
@click.option("--body", required=True, help="The user to update.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_user_for_workspace(workspace_gid: str, user_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a user in a workspace or organization"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = UsersApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_user_for_workspace(parsed_body, workspace_gid, user_gid, opts)
