# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

from typing import Any

import click
from asana import WebhooksApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession, resolve_body, resolve_workspace


@click.group("webhooks")
def webhooks_group() -> None:
    """Webhooks commands."""


@webhooks_group.command("create-webhook")
@click.option("--body", required=True, help="The webhook workspace and target.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def create_webhook(body: str, opt_fields: str | None) -> Any:
    """Establish a webhook"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = WebhooksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.create_webhook(parsed_body, opts)


@webhooks_group.command("delete-webhook")
@click.option("--webhook", required=True, help="Globally unique identifier for the webhook. If the method is called asynchronously, returns the request thread.")
@formatted
def delete_webhook(webhook: str) -> Any:
    """Delete a webhook"""
    session = AsanaSession.from_env()
    api = WebhooksApi(session.client)
    opts: dict[str, Any] = {}
    return api.delete_webhook(webhook)


@webhooks_group.command("get-webhook")
@click.option("--webhook", required=True, help="Globally unique identifier for the webhook.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_webhook(webhook: str, opt_fields: str | None) -> Any:
    """Get a webhook"""
    session = AsanaSession.from_env()
    api = WebhooksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_webhook(webhook, opts)


@webhooks_group.command("get-webhooks")
@click.option("--workspace", default=None, help="Workspace GID (falls back to ASANA_DEFAULT_WORKSPACE)")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--resource", default=None, help="Only return webhooks for the given resource.")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_webhooks(workspace: str | None, limit: int | None, offset: str | None, opt_fields: str | None, resource: str | None, paginate: bool) -> Any:
    """Get multiple webhooks"""
    resolved_workspace = resolve_workspace(workspace, required=True)
    session = AsanaSession.from_env(paginate=paginate)
    api = WebhooksApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    if resource is not None:
        opts["resource"] = resource
    return api.get_webhooks(resolved_workspace, opts)


@webhooks_group.command("update-webhook")
@click.option("--webhook", required=True, help="Globally unique identifier for the webhook.")
@click.option("--body", required=True, help="The updated filters for the webhook.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_webhook(webhook: str, body: str, opt_fields: str | None) -> Any:
    """Update a webhook"""
    parsed_body = resolve_body(body)
    session = AsanaSession.from_env()
    api = WebhooksApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_webhook(parsed_body, webhook, opts)
