# This file is auto-generated by tools/codegen.py — do not edit manually.
from __future__ import annotations

import json
from typing import Any

import click
from asana import WorkspacesApi

from asana_api_cli.formatter import formatted
from asana_api_cli.session import AsanaSession


@click.group("workspaces")
def workspaces_group() -> None:
    """Workspaces commands."""


@workspaces_group.command("add-user-for-workspace")
@click.argument("workspace_gid")
@click.option("--body", required=True, help="The user to add to the workspace.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def add_user_for_workspace(workspace_gid: str, body: str, opt_fields: str | None) -> Any:
    """Add a user to a workspace or organization"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = WorkspacesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.add_user_for_workspace(parsed_body, workspace_gid, opts)


@workspaces_group.command("get-workspace")
@click.argument("workspace_gid")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def get_workspace(workspace_gid: str, opt_fields: str | None) -> Any:
    """Get a workspace"""
    session = AsanaSession.from_env()
    api = WorkspacesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_workspace(workspace_gid, opts)


@workspaces_group.command("get-workspace-events")
@click.argument("workspace_gid")
@click.option("--sync", default=None, help="A sync token received from the last request, or none on first sync. Events will be returned from the point in time that the sync token was generated. *Note: On your first request, omit the sync tok...")
@formatted
def get_workspace_events(workspace_gid: str, sync: str | None) -> Any:
    """Get workspace events"""
    session = AsanaSession.from_env()
    api = WorkspacesApi(session.client)
    opts: dict[str, Any] = {}
    if sync is not None:
        opts["sync"] = sync
    return api.get_workspace_events(workspace_gid, opts)


@workspaces_group.command("get-workspaces")
@click.option("--limit", type=int, default=None, help="Results per page. The number of objects to return per page. The value must be between 1 and 100.")
@click.option("--offset", default=None, help="Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not pass...")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@click.option("--paginate", is_flag=True, default=False, help="Fetch all pages")
@formatted
def get_workspaces(limit: int | None, offset: str | None, opt_fields: str | None, paginate: bool) -> Any:
    """Get multiple workspaces"""
    session = AsanaSession.from_env(paginate=paginate)
    api = WorkspacesApi(session.client)
    opts: dict[str, Any] = {}
    if limit is not None:
        opts["limit"] = limit
    if offset is not None:
        opts["offset"] = offset
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.get_workspaces(opts)


@workspaces_group.command("remove-user-for-workspace")
@click.argument("workspace_gid")
@click.option("--body", required=True, help="The user to remove from the workspace.")
@formatted
def remove_user_for_workspace(workspace_gid: str, body: str) -> Any:
    """Remove a user from a workspace or organization"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = WorkspacesApi(session.client)
    opts: dict[str, Any] = {}
    return api.remove_user_for_workspace(parsed_body, workspace_gid)


@workspaces_group.command("update-workspace")
@click.argument("workspace_gid")
@click.option("--body", required=True, help="The workspace object with all updated properties.")
@click.option("--opt-fields", default=None, help="This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to in...")
@formatted
def update_workspace(workspace_gid: str, body: str, opt_fields: str | None) -> Any:
    """Update a workspace"""
    parsed_body = json.loads(body)
    session = AsanaSession.from_env()
    api = WorkspacesApi(session.client)
    opts: dict[str, Any] = {}
    if opt_fields is not None:
        opts["opt_fields"] = opt_fields
    return api.update_workspace(parsed_body, workspace_gid, opts)
