# Generated by asana-api <VERSION>
# Equivalent to: asana-api --access-token ...Zx9Q7w --set-default-header 'Authorization=Bearer ...7h3nd9' --proxy 'http://user:***@proxy.test:8080' tasks get-task --task 1

from __future__ import annotations

import json
import sys

import asana

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = '...Zx9Q7w'
configuration.proxy = 'http://user:***@proxy.test:8080'
api_client = asana.ApiClient(configuration)
api_client.set_default_header('Authorization', 'Bearer ...7h3nd9')

api_instance = asana.TasksApi(api_client)
opts = {}

result = api_instance.get_task('1', opts)

print(json.dumps(result, indent=2, ensure_ascii=False))

