# Generated by asana-api <VERSION>
# Equivalent to: asana-api --access-token DUMMY-TOKEN --host https://h.test/api --user-agent ua/1.0 --set-default-header X-Trace=abc tasks get-task --task 1

from __future__ import annotations

import json
import sys

import asana

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = 'DUMMY-TOKEN'
configuration.host = 'https://h.test/api'
api_client = asana.ApiClient(configuration)
api_client.set_default_header('X-Trace', 'abc')
api_client.user_agent = 'ua/1.0'

api_instance = asana.TasksApi(api_client)
opts = {}

result = api_instance.get_task('1', opts)

print(json.dumps(result, indent=2, ensure_ascii=False))

