# Generated by asana-api <VERSION>
# Equivalent to: asana-api tasks create-task --body -

from __future__ import annotations

import json
import os
import sys

import asana

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = os.environ['ASANA_ACCESS_TOKEN']
api_client = asana.ApiClient(configuration)

api_instance = asana.TasksApi(api_client)
body = json.load(sys.stdin)
opts = {}

result = api_instance.create_task(body, opts)

print(json.dumps(result, indent=2, ensure_ascii=False))

