# Generated by asana-api <VERSION>
# Equivalent to: asana-api tasks get-task --task 1 --exception-output json

from __future__ import annotations

import json
import os
import sys
import traceback

import asana
from asana.rest import ApiException

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = os.environ['ASANA_ACCESS_TOKEN']
api_client = asana.ApiClient(configuration)

api_instance = asana.TasksApi(api_client)
opts = {}

try:
    result = api_instance.get_task('1', opts)
except Exception as exc:
    sys.stderr.write("".join(traceback.format_exception_only(type(exc), exc)))
    qualified = f"{type(exc).__module__}.{type(exc).__qualname__}"
    if isinstance(exc, ApiException):
        raw_body = exc.body
        if isinstance(raw_body, (bytes, bytearray)):
            body_text = bytes(raw_body).decode("utf-8", errors="replace")
        elif isinstance(raw_body, str):
            body_text = raw_body
        else:
            body_text = None
        envelope = {
            "exception": qualified,
            "status": exc.status,
            "reason": exc.reason,
            "body": body_text,
            "headers": dict(exc.headers) if exc.headers is not None else None,
        }
    else:
        envelope = {"exception": qualified, "reason": str(exc)}
    print(json.dumps(envelope, indent=2, ensure_ascii=False))
    sys.exit(3)

print(json.dumps(result, indent=2, ensure_ascii=False))

