# Generated by asana-api <VERSION>
# Equivalent to: asana-api tasks get-tasks --workspace 111 --opt-fields name,assignee.name --limit 50 --item-limit 200

from __future__ import annotations

import json
import os
import sys

import asana

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = os.environ['ASANA_ACCESS_TOKEN']
api_client = asana.ApiClient(configuration)

api_instance = asana.TasksApi(api_client)
opts = {'limit': 50, 'opt_fields': 'name,assignee.name', 'workspace': '111'}

result = list(api_instance.get_tasks(opts, item_limit=200))

print(json.dumps(result, indent=2, ensure_ascii=False))

