# Generated by asana-api <VERSION>
# Equivalent to: asana-api tasks get-tasks --workspace 111 --output table

from __future__ import annotations

import json
import os
import sys
from typing import Any

import asana
from tabulate import tabulate

def scalar_text(value: Any) -> str:
    """Single-cell text representation.

    Scalars (None / str / int / float / bool) are stringified naturally;
    nested containers (dict / list) are JSON-encoded so that text / csv /
    table cells use JSON syntax (``{"a":"b"}``) rather than Python repr
    (``{'a': 'b'}``).
    """
    if value is None or isinstance(value, (str, int, float, bool)):
        return str(value)
    try:
        return json.dumps(value, ensure_ascii=False)
    except (TypeError, ValueError):
        return str(value)

def to_rows(data: Any) -> list[dict[str, Any]] | None:
    """Convert data into a list of dicts for table/csv. Return None if not possible."""
    if isinstance(data, list):
        if not data:
            return []
        # A jq yield can produce a mixed list (e.g. `[.data[0], .data | length]`)
        # which has no clean column layout. Require homogeneous shape.
        if all(isinstance(item, dict) for item in data):
            return data
        if not any(isinstance(item, dict) for item in data):
            return [{"value": v} for v in data]
        return None
    if isinstance(data, dict):
        return [data]
    return None

def format_table(rows: list[dict[str, Any]]) -> str:
    """Table text for *rows*. Pure (no I/O); the caller guards the empty case."""
    return tabulate(rows, headers="keys", tablefmt="simple")

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = os.environ['ASANA_ACCESS_TOKEN']
api_client = asana.ApiClient(configuration)

api_instance = asana.TasksApi(api_client)
opts = {'workspace': '111'}

result = list(api_instance.get_tasks(opts))

rows = to_rows(result)
if rows is None:
    print(scalar_text(result))
elif rows:
    rows = [{k: scalar_text(v) for k, v in row.items()} for row in rows]
    print(format_table(rows))

