# Generated by asana-api <VERSION>
# Equivalent to: asana-api tasks get-tasks --workspace 111 --output csv

from __future__ import annotations

import csv
import io
import json
import os
import sys
from typing import Any

import asana

def scalar_text(value: Any) -> str:
    """Single-cell text representation.

    Scalars (None / str / int / float / bool) are stringified naturally;
    nested containers (dict / list) are JSON-encoded so that text / csv /
    table cells use JSON syntax (``{"a":"b"}``) rather than Python repr
    (``{'a': 'b'}``).
    """
    if value is None or isinstance(value, (str, int, float, bool)):
        return str(value)
    try:
        return json.dumps(value, ensure_ascii=False)
    except (TypeError, ValueError):
        return str(value)

def to_rows(data: Any) -> list[dict[str, Any]] | None:
    """Convert data into a list of dicts for table/csv. Return None if not possible."""
    if isinstance(data, list):
        if not data:
            return []
        # A jq yield can produce a mixed list (e.g. `[.data[0], .data | length]`)
        # which has no clean column layout. Require homogeneous shape.
        if all(isinstance(item, dict) for item in data):
            return data
        if not any(isinstance(item, dict) for item in data):
            return [{"value": v} for v in data]
        return None
    if isinstance(data, dict):
        return [data]
    return None

def format_csv(rows: list[dict[str, Any]], *, with_bom: bool = False) -> str:
    """CSV text for *rows* (RFC 4180, CRLF record terminators). Pure (no I/O).

    Empty *rows* → empty string. The caller writes the result through the
    binary stdout layer so the CRLF terminators are not doubled on Windows.
    """
    if not rows:
        return ""
    buf = io.StringIO()
    if with_bom:
        buf.write("\ufeff")
    # Asana responses often have optional fields that appear on some rows
    # and not others (e.g. ``due_on``). Collect the union of keys across
    # all rows so no row's data is silently dropped.
    # ``dict.fromkeys`` preserves insertion order (Python 3.7+), giving a
    # stable column order based on first appearance.
    fieldnames = list(dict.fromkeys(key for row in rows for key in row))
    # RFC 4180: CRLF between records; newlines inside a field stay verbatim.
    writer = csv.DictWriter(buf, fieldnames=fieldnames, lineterminator="\r\n")
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = os.environ['ASANA_ACCESS_TOKEN']
api_client = asana.ApiClient(configuration)

api_instance = asana.TasksApi(api_client)
opts = {'workspace': '111'}

result = list(api_instance.get_tasks(opts))

rows = to_rows(result)
if rows is None:
    print(scalar_text(result))
elif rows:
    rows = [{k: scalar_text(v) for k, v in row.items()} for row in rows]
    text = format_csv(rows, with_bom=False)
    if text:
        sys.stdout.flush()
        sys.stdout.buffer.write(text.encode(sys.stdout.encoding or "utf-8"))
        sys.stdout.buffer.flush()

