# Generated by asana-api <VERSION>
# Equivalent to: asana-api tasks get-tasks --workspace 111 --query '.[].name'

from __future__ import annotations

import json
import os
import sys

import asana
import jq  # requires: pip install jq

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

configuration = asana.Configuration()
configuration.access_token = os.environ['ASANA_ACCESS_TOKEN']
api_client = asana.ApiClient(configuration)

api_instance = asana.TasksApi(api_client)
opts = {'workspace': '111'}

result = list(api_instance.get_tasks(opts))

try:
    results = jq.all('.[].name', result)
except ValueError as exc:
    sys.stderr.write(f"Invalid jq expression: {exc}\n")
    sys.exit(2)
for value in results:
    print(json.dumps(value, indent=2, ensure_ascii=False))

