"""Golden snapshots of generated python-asana scripts for representative commands.

Each case pins the full output of ``asana-api --generate-python <args>`` to a
committed fixture under ``tests/fixtures/generate_python/``. A renderer change
shows up as a reviewable fixture diff; the equivalence tests in
``test_codegen.py`` prove the *behavior* matches the CLI, while these pin the
emitted *text*.

The cases are driven through the real ``main`` tree (so global-option
propagation and the ``--version`` path are exercised) in generate mode, which
needs no token and makes no network call. ``sys.argv`` is set per case so the
provenance header is the canonical command; the volatile version value on the
``# Generated by`` line is normalized to ``<VERSION>`` so the snapshots survive
dependency bumps. The surface still depends on the SDK version, so — like
``test_cli_surface.py`` — the comparison is skipped on a non-pinned ``asana``.

Regenerate after an intentional renderer change::

    UPDATE_GENERATE_SNAPSHOTS=1 uv run pytest tests/test_generate_python_snapshots.py
"""

from __future__ import annotations

import os
import re
import sys
from importlib.metadata import version
from pathlib import Path

import pytest
from _cli_runner import full_output, make_runner

from asana_api_cli.cli import main

FIXTURES = Path(__file__).parent / "fixtures" / "generate_python"
_UPDATE = os.environ.get("UPDATE_GENERATE_SNAPSHOTS") == "1"

_SNAPSHOT_ASANA_VERSION = "5.2.4"
pytestmark = pytest.mark.skipif(
    version("asana") != _SNAPSHOT_ASANA_VERSION,
    reason=(
        f"generated-code snapshots pinned to asana=={_SNAPSHOT_ASANA_VERSION}; "
        f"installed asana=={version('asana')}"
    ),
)

# name -> argv after "asana-api" (the command exactly as a user would type it,
# minus --generate-python which the harness adds). Chosen to cover every layer.
_CASES: dict[str, list[str]] = {
    # config(env token) + single-object call + direct json
    "get_task": ["tasks", "get-task", "--task", "1234"],
    # iterator + opts + per-call kwargs
    "get_tasks_opts": [
        "tasks",
        "get-tasks",
        "--workspace",
        "111",
        "--opt-fields",
        "name,assignee.name",
        "--limit",
        "50",
        "--item-limit",
        "200",
    ],
    # body literal (true/false/null -> Python), non-iterator
    "create_task_body": [
        "tasks",
        "create-task",
        "--body",
        '{"data": {"name": "New", "completed": false}}',
    ],
    # body @file: read at the generated script's run time (C-9)
    "create_task_body_file": ["tasks", "create-task", "--body", "@new-task.json"],
    # body - : read stdin at the generated script's run time (C-9)
    "create_task_body_stdin": ["tasks", "create-task", "--body", "-"],
    # csv converters inlined (Any import, byte-write)
    "output_csv": ["tasks", "get-tasks", "--workspace", "111", "--output", "csv"],
    # text converters inlined
    "output_text": ["tasks", "get-task", "--task", "1", "--output", "text"],
    # table: the tabulate import + inlined format_table layer
    "output_table": ["tasks", "get-tasks", "--workspace", "111", "--output", "table"],
    # --query: jq dependency + per-yield render
    "query": ["tasks", "get-tasks", "--workspace", "111", "--query", ".[].name"],
    # --exception-output: try/except + envelope + exit 3
    "error_envelope": ["tasks", "get-task", "--task", "1", "--exception-output", "json"],
    # --debug: redactor.py inlined + with-wrap
    "debug": ["tasks", "get-task", "--task", "1", "--debug"],
    # upload: multibyte_filename.py inlined + with-wrap
    "upload_multibyte": [
        "attachments",
        "create-attachment-for-object",
        "--file",
        "/tmp/あ.png",
        "--multibyte-filenames",
    ],
    # bulk config: literal token, host, user-agent, default header
    "config_heavy": [
        "--access-token",
        "DUMMY-TOKEN",
        "--host",
        "https://h.test/api",
        "--user-agent",
        "ua/1.0",
        "--set-default-header",
        "X-Trace=abc",
        "tasks",
        "get-task",
        "--task",
        "1",
    ],
    # --generate-python --version: version.py inlined + print
    "version": ["--version"],
}


def _normalize(code: str) -> str:
    """Replace the volatile provenance version with a stable placeholder."""
    return re.sub(
        r"^# Generated by asana-api .*$",
        "# Generated by asana-api <VERSION>",
        code,
        count=1,
        flags=re.MULTILINE,
    )


def _generate(monkeypatch: pytest.MonkeyPatch, argv: list[str]) -> str:
    monkeypatch.delenv("ASANA_ACCESS_TOKEN", raising=False)
    monkeypatch.delenv("ASANA_DEFAULT_WORKSPACE", raising=False)
    monkeypatch.setattr(sys, "argv", ["asana-api", "--generate-python", *argv])
    result = make_runner().invoke(main, ["--generate-python", *argv])
    assert result.exit_code == 0, full_output(result)
    return _normalize(result.stdout)


@pytest.mark.parametrize("name", list(_CASES))
def test_snapshot_matches(name: str, monkeypatch: pytest.MonkeyPatch) -> None:
    actual = _generate(monkeypatch, _CASES[name])
    fixture = FIXTURES / f"{name}.py"
    if _UPDATE:
        fixture.parent.mkdir(parents=True, exist_ok=True)
        fixture.write_text(actual, encoding="utf-8")
        return
    assert fixture.exists(), (
        f"missing snapshot {fixture.name}; run "
        "UPDATE_GENERATE_SNAPSHOTS=1 uv run pytest tests/test_generate_python_snapshots.py"
    )
    assert actual == fixture.read_text(encoding="utf-8"), (
        f"generated code for {name!r} drifted from {fixture.name}; review the diff "
        "and, if intended, regenerate with UPDATE_GENERATE_SNAPSHOTS=1"
    )


@pytest.mark.parametrize("name", list(_CASES))
def test_snapshot_compiles(name: str) -> None:
    # The committed fixture on disk must be valid Python (with the placeholder
    # header). Reads the file rather than regenerating, so it also catches a
    # corrupted / hand-edited fixture — distinct coverage from
    # ``test_snapshot_matches``.
    fixture = FIXTURES / f"{name}.py"
    if not fixture.exists():
        pytest.skip(f"snapshot {fixture.name} not generated yet")
    compile(fixture.read_text(encoding="utf-8"), f"<{name}>", "exec")
